server:
  port: 80
application:
  version: '@project.version@-${random.int}'
spring:
  application:
    name: "klipper-service"
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/